### ISSUE TITLE
Wordpress issue On HTTPS

### ISSUE THREAD

**Issue by Dinesh-Ramakrishnan** [openshift/wordpress-example#1]
I installed Wordpress App on my Gear as per the guidelines provided in this repo. 
When I lauched the Admin page, I am not able to login, Later I changed the Login Form Post URL from http to https it worked.
I faced the same problem with Codeigniter and my solution is posted here.

https://openshift.redhat.com/community/forums/openshift/https-key-not-set-in-server-over-https-protocol
```
if ((isset($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) !== 'off' ) || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https'))
{
/// On HTTPS URL
}
```

Please check and update the code accordingly.

**Comment by luciddreamz** [comment]
For reference, you can force HTTPS by uncommenting lines 4 and 5 from the provided .htaccess file:
https://github.com/openshift/wordpress-example/blob/master/.openshift/config/.htaccess#L4
