### ISSUE TITLE
SMTP plugin

### ISSUE THREAD

**Issue by emzo** [openshift/wordpress-example#14]
Since OpenShift does not send outbound email, it would make sense to suggest users install an SMTP plugin so that WordPress generated emails (password resets, new user registrations etc.) may be sent. [SMTP](http://wordpress.org/extend/plugins/smtp/) is  simple to set up, and has worked perfectly for me sending outbound mail via Gmail.

Maybe we could create a Wiki page explaining this, adding links to other suitable plugins, so as not to be biased towards a single plugin?

**Comment by asrob** [comment]
I think OpenShift can send email, because I got one a few minutes ago, so can we close this issue?

**Comment by hakib** [comment]
I'm trying to send an email from openshift using the wp-mail-smtp and my personal account as suggested above and I got an email from google that there is suspicious activity in the account and that the mail was blocked. 

@jiteshp - How did you work around that ? 

Thanks.

**Comment by jiteshp** [comment]
I did not get any such email from Google.
However you may want to check if your one time app specific password is ok.

**Comment by jiteshp** [comment]
@asrob yes, i think the issue can be closed.

**Comment by mkdizajn** [comment]
@hakib, 

I was having the same issue as you with sending via gmail with that wp smtp plugin, that is couse gmail restrected some policy recently so we can't use that plugin anymore.

I did find another great plugin that works with gmail and it's using mandrill as a service, give it a try, it works 100% and it rocks!

https://wordpress.org/plugins/wpmandrill/

cheers, k

**Comment by gavinengel** [comment]
@mkdizajn Thanks for that.

**Comment by luciddreamz** [comment]
For reference - we would recommend using the SendGrid Marketplace add-on for mail deliver with the OpenShift WordPress QuickStart. Full installation instructions are available in our Dev Portal: https://developers.openshift.com/en/marketplace-sendgrid.html#php-wordpress
